### PR TITLE
Minor bugfixes

### PR DESCRIPTION
**Pull request by markwoon**
Biggest change is the modification to display the PMID when displaying literature.

### CODE REVIEW

**Comment by markwoon** [comment]
Also added IDEA config files as discussed.

**Comment by mkutmon** [comment]
Two small questions:
- what are the "Fix line endings" commits about? How can we prevent this from happening again?
- in the IntelliJ IDE config files - do we need to update those manually? (e.g. .idea/libraries/lib.xml --> if a library is updated/added/removed)

**Comment by markwoon** [comment]
> what are the "Fix line endings" commits about? How can we prevent this from happening again?

The problem is discussed here: https://help.github.com/articles/dealing-with-line-endings/.  You can Google for lengthier discussions about it.

How to avoid in the future?  Per GitHub's suggestions:  set autocrlf to true and use .gitattributes to make sure everyone's on the same page regarding what types of files should have what types of line endings.

> in the IntelliJ IDE config files - do we need to update those manually? (e.g. .idea/libraries/lib.xml --> if a library is updated/added/removed)

I'm afraid so, unless PV switches to Gradle/Maven with automatic dependency management.

**Comment by mkutmon** [comment]
Ok! Ah, you already created a .gitattributes file. Perfect, thanks!

**Pull request merged**
