### PR TITLE
Support importing of data for pathways (e.g. Z-scores)

### PR DESCRIPTION
**Pull request by egonw**
Tina, I leave it to your discretion to apply this patch or not. cc @marvinm2

### CODE REVIEW

**Comment by mkutmon** [comment]
@egonw I think that change should be fine. Does anything else need to be changed to make visualization on pathway nodes possible?

**Comment by egonw** [comment]
No, I don't think so. @marvinm2, agreed?

**Comment by marvinm2** [comment]
Well, I haven't tested it, so I don't know whether the visualisation options work on pathway nodes (with or without the rounded rectangle box)

**Comment by egonw** [comment]
The mapping of data onto the nodes works, but I haven't tried it with rounded

**Comment by egonw** [comment]
Oops, wrong button

**Pull request merged**
