### PR TITLE
Remove a literature reference #19

### PR DESCRIPTION
**Pull request by JonathanMELIUS**
When a pathway element is deleted, also remove the literature reference link to the pathway element.

### CODE REVIEW

**Comment by mkutmon** [comment]
Hi Jonathan. I had a quick look at the commit. I am missing the step, where you check if the literature reference is referenced from any other object. It is possible that the same paper might be linked from different pathway elements. If you then simply delete the reference, then we will have the issue that something references to a pubref that has been deleted.

**Comment by JonathanMELIUS** [comment]
Hi Tina, yes you're right. I missed that case.

**Comment by mkutmon** [comment]
Looks like the function to check for existing references was already there?

**Comment by JonathanMELIUS** [comment]
https://github.com/PathVisio/pathvisio/pull/20/commits/af5866b7049998ae392cb810ad0329562cee1b29
`getBiopax().hasReferences(node)` will check the temporary list of the pathway's dataObjects.
The datanode that is being removed doesn't appear in the temporary list.
So if `hasReferences` return false, no other datanode use this reference, then the literature reference can be delete.

**Pull request merged**
