### PR TITLE
Some root cleanup

### PR DESCRIPTION
**Pull request by egonw**

### CODE REVIEW

**Comment by larsgw** [comment]
To replace Travis we can use:

```yaml
name: Java CI

on:
  push:
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        openjdk: [8, 11, 14]

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: ${{ matrix.openjdk }}
        distribution: 'temurin'
    - name: Build with Ant
      run: ant exe
```

With a badge: [Java CI](https://github.com/larsgw/pathvisio/actions/workflows/ant.yml)

**Comment by egonw** [comment]
@larsgw, I think we can have different compile scenario's for different branches, right?

**Comment by larsgw** [comment]
Yes, maybe even just by changing the yml file in that branch.

**Comment by egonw** [comment]
This can be merged.

**Pull request merged**
