### PR TITLE
BridgeDb 2.3.7 and Derby 10.5.3.0

### PR DESCRIPTION
**Pull request by egonw**
Allows reading the most recent COVID-19 related ID mapping databases. Created against the 3.3.0 release, but there is no branch for that?

image

### CODE REVIEW

**Comment by egonw** [comment]
Mappings in action:

image

**Comment by mkutmon** [comment]
do these required Java 11?

**Comment by egonw** [comment]
No, it should not. The BridgeDb 2.3 release is Java 8. Java 11 is only in master, but even that one should work with Java8.

**Comment by DeniseSl22** [comment]
This should also accommodate for the disease mapping files if I'm correct :)

**Comment by DeniseSl22** [comment]
I've tested the disease mapping files with bridgedb 2.3.8 libraries, and it works :D .
So please update PV and release a new version, so I can release the new disease mapping files @mkutmon 

image

**Comment by egonw** [comment]
cc @Chris-Evelo

**Comment by Chris-Evelo** [comment]
I do not see that on https://bridgedb.github.io/pages/mappingdbs.html yet? Or should I look for that somewhere else?

Also, there is a larger initiative to optimize disease mappings (MONOD mappings) that I think Freddie is aware of and that is already available through OxO. 

That also led to a discussion on mapping file standards. I will forward the last email from that thread to all of you.

I think:
1) The suggestion for a standard mapping file format (and the provenance that should accompany that) is really relevant and aligns with what Alasdair Gray suggested recently in our own ID mapping group.
2) Mentioning that I think Alasdair and Nick and others involved in the ID mapping discussions should see these issues too. Not sure what is the best way to do that.
3) I think we should aline with that initiative and not create our won mappings. If we can improve on what they do we should feed that back to them.
4) These are mappings for disease ontology terms, not mere database IDs, although I agree the difference can be flimsy it would be good to keep that separation. So in that sense, I would, at least in the long run, not even want to find them in the BridgeDb mapping repo but in OxO's repository (note that it is important for these recommended interoperability resources to have their own niche, both for strategic and practical reasons. People will want to know what to use for what).
5) In line with that, it would be nice if PathVisio and WikiPathways could support OxO API calls to use disease ontology mappings whenever needed. But I suppose that will take a bit more time.

**Comment by egonw** [comment]
> I do not see that on https://bridgedb.github.io/pages/mappingdbs.html yet? Or should I look for that somewhere else?

If you are looking for the BridgeDb Java library of this patch, then that's indeed the wrong page, and you should look at: https://bridgedb.github.io/pages/download.html

Otherwise, this patch is not about BridgeDb. it's just about disease functionality in PathVisio. I am not sure Alasdair and Nick need to see this patch.

**Comment by Chris-Evelo** [comment]
> > I do not see that on https://bridgedb.github.io/pages/mappingdbs.html yet? Or should I look for that somewhere else?
> 
> If you are looking for the BridgeDb Java library of this patch, then that's indeed the wrong page, and you should look at: https://bridgedb.github.io/pages/download.html
> 
> Otherwise, this patch is not about BridgeDb. it's just about disease functionality in PathVisio. I am not sure Alasdair and Nick need to see this patch.

I wasn't looking for the patch but for the resulting mapping file. Sorry if that wasn't clear.

**Comment by egonw** [comment]
Ah, okay. But that's not related to this patch. If new data sources are defined, this still requires a code change. In the past, only by BridgeDb Java lib updates. Nowadays, tools using BridgeDb can locally install extra data sources. But mapping files (Derby files) cannot.

This patch is only about letting PathVisio know about newer data sources. The mapping file that use the datasources are independent from this.

**Comment by DeniseSl22** [comment]
> I do not see that on https://bridgedb.github.io/pages/mappingdbs.html yet? Or should I look for that somewhere else?

No, because I thought it wouldn't make sense to release a mapping file, which cannot be used within either PV, WP, and Bioconductor. The only place were we can use it, is the BridgeDb API (If the bridgedb libraries there have been updated to 2.3.8).

> Also, there is a larger initiative to optimize disease mappings (MONOD mappings) that I think Freddie is aware of and that is already available through OxO.
> 
> That also led to a discussion on mapping file standards. I will forward the last email from that thread to all of you.

I saw your emails on that, thank you.

> I think:
> 
> 1. The suggestion for a standard mapping file format (and the provenance that should accompany that) is really relevant and aligns with what Alasdair Gray suggested recently in our own ID mapping group.

Wouldn't this then also be useful for the other mapping files we create?

> 2. Mentioning that I think Alasdair and Nick and others involved in the ID mapping discussions should see these issues too. Not sure what is the best way to do that.

I've met Alasdair during the Biohackathon 2019, discussed my work briefly. And I send Nick messages from time to time, when I see something is not working on identifiers.org .

> 3. I think we should aline with that initiative and not create our won mappings. If we can improve on what they do we should feed that back to them.

I'm not creating my own mappings, I'm using the ones from wikidata. I need this for work on the Blau book (among other things). I've also talked to some people from Disgenet during the biohackathon 2019, and they wanted their mappings to be a part of this bridgedb file too. Still working out the licence info with them.... So I think there are quite some people who would like this disease mapping option now, compared to having to wait for an initiative (from a hackathon in 2015?).

> 4. These are mappings for disease ontology terms, not mere database IDs, although I agree the difference can be flimsy it would be good to keep that separation. So in that sense, I would, at least in the long run, not even want to find them in the BridgeDb mapping repo but in OxO's repository (note that it is important for these recommended interoperability resources to have their own niche, both for strategic and practical reasons. People will want to know what to use for what).
> 5. In line with that, it would be nice if PathVisio and WikiPathways could support OxO API calls to use disease ontology mappings whenever needed. But I suppose that will take a bit more time.

Yes, the above sounds great, but is not there yet (and will take some time to develop). Better use what we have now, then create a new version of PV and the WP website, and then think about new features...

**Comment by Chris-Evelo** [comment]
> > I do not see that on https://bridgedb.github.io/pages/mappingdbs.html yet? Or should I look for that somewhere else?
> 
> No, because I thought it wouldn't make sense to release a mapping file, which cannot be used within either PV, WP, and Bioconductor. The only place were we can use it, is the BridgeDb API (If the bridgedb libraries there have been updated to 2.3.8).

Yes, that makes sense. I wasn't aware of that.
> 
> > Also, there is a larger initiative to optimize disease mappings (MONOD mappings) that I think Freddie is aware of and that is already available through OxO.
> > That also led to a discussion on mapping file standards. I will forward the last email from that thread to all of you.
> 
> I saw your emails on that, thank you.
> 
> > I think:
> > 
> > 1. The suggestion for a standard mapping file format (and the provenance that should accompany that) is really relevant and aligns with what Alasdair Gray suggested recently in our own ID mapping group.
> 
> Wouldn't this then also be useful for the other mapping files we create?
Yes, I think so. And for the linksets that should be easy. But we will need to contribute to the discussion about what should be captured as provenance. I already started doing that on Github page for MONOD.
> 
> > 1. Mentioning that I think Alasdair and Nick and others involved in the ID mapping discussions should see these issues too. Not sure what is the best way to do that.
> 
> I've met Alasdair during the Biohackathon 2019, discussed my work briefly. And I send Nick messages from time to time, when I see something is not working on identifiers.org .
We have regular discussions with both of them in a monthly ID mapping telco, primarily related to FAIRplus work. Nick is also on the list of SAB members for BridgeDb. 
> 
> > 1. I think we should aline with that initiative and not create our won mappings. If we can improve on what they do we should feed that back to them.
> 
> I'm not creating my own mappings, I'm using the ones from wikidata. I need this for work on the Blau book (among other things). I've also talked to some people from Disgenet during the biohackathon 2019, and they wanted their mappings to be a part of this bridgedb file too. Still working out the licence info with them.... So I think there are quite some people who would like this disease mapping option now, compared to having to wait for an initiative (from a hackathon in 2015?).
OK, makes sense. then we might just want to make sure that the ones on wikidata are aligned with MONOD

> 
> > 1. These are mappings for disease ontology terms, not mere database IDs, although I agree the difference can be flimsy it would be good to keep that separation. So in that sense, I would, at least in the long run, not even want to find them in the BridgeDb mapping repo but in OxO's repository (note that it is important for these recommended interoperability resources to have their own niche, both for strategic and practical reasons. People will want to know what to use for what).
> > 2. In line with that, it would be nice if PathVisio and WikiPathways could support OxO API calls to use disease ontology mappings whenever needed. But I suppose that will take a bit more time.
> 
> Yes, the above sounds great, but is not there yet (and will take some time to develop). Better use what we have now, then create a new version of PV and the WP website, and then think about new features...
Agree, about that order of things. But we should try to prevent making BridgeDb into a Swiss army knife (which still involves work) and use dedicated tools like OxO that we actually need for other projects too (FAIRplus and FNS Cloud anyway), whenever possible.

**Pull request closed without merging**
