### PR TITLE
Derby 10.14.2.0

### PR DESCRIPTION
**Pull request by egonw**
Tina, can you plz double check if ID mapping works for you too? Derby 10.14 is the most recent version compatible with Java 8: https://db.apache.org/derby/derby_downloads.html

It fixes for me loading the Derby file @DeniseSl22 had trouble with loading.

### CODE REVIEW

**Comment by mkutmon** [comment]
Are these OSGi bundles? I get OSGi errors when starting PathVisio
`org.eclipse.osgi.service.pluginconversion.PluginConversionException: Could not find a META-INF/MANIFEST.MF, plugin.xml or a fragment.xml`

**Comment by egonw** [comment]
Oh, shit... I guess not.

**Comment by mkutmon** [comment]
should I wait for this for the point release or is it fine to continue?

**Comment by egonw** [comment]
I had a check, and looking from [DERBY-3730](https://issues.apache.org/jira/browse/DERBY-3730) I would say they are meant to be OSGI-compatible.

OK, I'll download the binary distribution. There the derby.jar certainly does have a MANIFEST:

```
$ jar tvf derby.jar | grep MAN
  1419 Fri Apr 06 18:10:12 CEST 2018 META-INF/MANIFEST.MF
```

**Comment by egonw** [comment]
New PR with jars from the binary distribution instead of Maven Central (should not matter; but apparently it does): https://github.com/PathVisio/pathvisio/pull/130

**Pull request closed without merging**
